name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@{version}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          COMMENTS_ACTIVITY: "Gave a comment on {ID} in {REPO}"
          ISSUE_OPENED: "Made Issue {ID} in {REPO}"
          ISSUE_CLOSED: "Closed Issue {ID} in {REPO}"
          PR_OPENED: "Made Pull request {ID} in {REPO}"
          PR_CLOSED: "Closed Pull request {ID} in {REPO}"
          PR_MERGED: "Merged Pull request {ID} in {REPO}"
